[tool.poetry]
name = 'maltsev-repeater'
description = ''
version = '1.0.1'

repository = 'https://github.com/victormaltsev/Maltsev.Repeater'
readme = 'README.md'
license = 'MIT'
authors = ['Victor Maltsev <git@victormaltsev.com>']
